module Collatz where

-- Collatz problem: model the famous Collatz sequence. The Collatz sequence for
-- a number `n` is the sequence of numbers generated by repeatedle aplying the
-- following operations until the number is equal to 1.

-- - If the number is even, divide it by two.
-- - If the number is odd, triple it and add one.

-- For further details see https://en.wikipedia.org/wiki/Collatz_conjecture

open import Data.Empty using (⊥; ⊥-elim)
open import Data.Unit using (⊤)
open import Relation.Binary.PropositionalEquality using (_≡_; refl; cong)
open import Data.Nat using (ℕ; zero; suc; _+_; _*_)
open import Data.Sum using (_⊎_; inj₁; inj₂)
open import EvenOrOdd using (evenOrOdd; evenOddDisjoint; Even; Odd; zero; one; step)
open import Data.Bool.Base using (Bool; true; false)

-- Divide by 2 even numbers exploiting their evenness
_/2 : {n : ℕ} → Even n → ℕ
zero /2 = zero
step x /2 = suc (x /2)

-- Check that `6 / 2 = 3`
_ : (step (step (step zero))) /2 ≡ 3
_ = refl

-- Simple way to represent positive natural numbers. With that we can implicitly
-- constraint a number to be positive (as a matter of fact, I should say, to
-- exclude zero)
Positive : ℕ -> Set
Positive zero = ⊥
Positive _    = ⊤

-- Define a single step of Collatz sequence
collatzStep : (n : ℕ) → {_ : Positive n} → ℕ
collatzStep n with evenOrOdd n
... | inj₁ even = even /2
... | inj₂ odd = (n * 3) + 1

-- Prove the correctness of `collatzStep` for the even case
collatzStep-even : ∀ {n : ℕ} {p : Positive n} → (e : Even n) → collatzStep n {p} ≡ e /2
collatzStep-even {n} {p} e with evenOrOdd n
... | inj₁ e' = cong _/2 (even-unique e' e)
  where
    even-unique : ∀ {n} → (e₁ : Even n) → (e₂ : Even n) → e₁ ≡ e₂
    even-unique zero zero = refl
    even-unique (step e₁) (step e₂) = cong step (even-unique e₁ e₂)
... | inj₂ o = ⊥-elim (evenOddDisjoint n e o)  -- Contradiction!

-- Prove the correctness of `collatzStep` for the odd case
collatzStep-odd : ∀ {n : ℕ} {p : Positive n} → Odd n → collatzStep n {p} ≡ n * 3 + 1
collatzStep-odd {n} {p} o with evenOrOdd n
... | inj₁ e = ⊥-elim (evenOddDisjoint n e o)
... | inj₂ o' = refl

-- Nice syntax to represent a sequence
infixr 4 _followedBy_
data Reaches1 : ℕ → Set where
  one : Reaches1 1
  _followedBy_ : (n : ℕ) {p : Positive n} → (Reaches1 (collatzStep n {p})) → Reaches1 n

-- Prove that zero is not part of the Collatz sequence
zero-does-not-reach-1 : Reaches1 0 → ⊥
zero-does-not-reach-1 (_followedBy_ _ {p} _) = p

-- Prove that 4 will reach 1
reaches1-4 : Reaches1 4
reaches1-4 = 4 followedBy 2 followedBy one

-- Prove that 5 will reach 1
reaches1-5 : Reaches1 5
reaches1-5 = 5 followedBy 16 followedBy 8 followedBy reaches1-4

-- Prove that 7 will reach 1
reaches1-7 : Reaches1 7
reaches1-7 = 7 followedBy
             22 followedBy
             11 followedBy
             34 followedBy
             17 followedBy
             52 followedBy
             26 followedBy
             13 followedBy
             40 followedBy
             20 followedBy
             10 followedBy
             5 followedBy
             16 followedBy
             8 followedBy
             reaches1-4

-- Since the Collatz conjecture is an open mathematical problem you are
-- dispensed to prove it 😁
